server:
  port: 8080
  
spring:
  mvc:
    view:
      prefix: /WEB-INF/pages/ 
      suffix: .jsp

  datasource:
    url: jdbc:mysql://localhost:3306/db_parkingsystem
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
